<a href="https://colab.research.google.com/github/pinpan123/Email-spam-checker/blob/main/Email_spam_checker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
import pandas as pd

In [10]:
import nltk
from nltk.corpus import stopwords
import string


In [11]:
from google.colab import files
uploaded=files.upload()

Saving spamham.csv to spamham.csv


In [12]:

df = pd.read_csv('spamham.csv')

In [13]:
df.head(10)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [14]:
df.shape

(5728, 2)

In [15]:
df.columns

Index(['text', 'spam'], dtype='object')

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.shape

(5695, 2)

In [18]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [26]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [27]:
def process_text(text):
  nopunch=[char for char in text if char not in string.punctuation]
  nopunch=''.join(nopunch)
  clean_words=[word for word in nopunch.split() if word.lower() not in stopwords.words('english')]
  return clean_words

In [28]:
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
message_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [30]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(message_bow,df['spam'],test_size=0.20,random_state=0)






In [31]:
message_bow.shape

(5695, 37229)

In [34]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [35]:
print(classifier.predict(X_train))
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [36]:

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print( classification_report(y_train,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_train,pred))
print()
print('Accuracy  :',accuracy_score(y_train,pred))





              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy  : 0.9971466198419666


In [39]:
print(classifier.predict(X_test))
print(y_test.values)


[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [41]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_test)
print( classification_report(y_test,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_test,pred))
print()
print('Accuracy  :',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion Matrix:
 [[862   8]
 [  1 268]]

Accuracy  : 0.9920983318700615
